// Cloudflare integration for the hosted Email Forwarding Manager (Worker + D1).
//
// This is the async D1 / WebCrypto port of the local app's scripts/cloudflare.mjs.
// The Worker calls the Cloudflare API directly (server-to-server, so CORS does
// not apply) — no separate proxy is needed.
//
// The API token is stored ENCRYPTED at rest in the D1 `settings` table using
// AES-256-GCM (WebCrypto). The 32-byte key is the Worker secret `ENC_KEY`
// (base64), set via `wrangler secret put ENC_KEY`. This protects the token if
// the D1 contents leak without the secret.
//
// Forwarding model:
//   * 1 destination  -> a Cloudflare Email Routing *rule* with a `forward`
//                       action (a "simple alias", no Worker involved).
//   * N destinations  -> a single fan-out *Worker* whose source embeds every
//                       multi-destination mapping, plus a routing rule with a
//                       `worker` action pointing at that Worker.

const CF_BASE = "https://api.cloudflare.com/client/v4";
const PER_PAGE = 50;
const DEFAULT_WORKER = "email-fanout";
const SCRIPT_FILE = "index.js";

// The fan-out Worker embeds every multi-destination mapping as JS object
// literals, which the Cloudflare rules API cannot read back. To make Cloudflare
// the source of truth we also embed a machine-readable manifest (base64 JSON)
// in a delimited comment, so the app can reconstruct those mappings by reading
// the deployed Worker's source.
const MANIFEST_START = "/*__EFM_MANIFEST__";
const MANIFEST_END = "__EFM_MANIFEST__*/";

function apiError(status, message) {
  return Object.assign(new Error(message), { status });
}

// ---------- Encryption (WebCrypto AES-256-GCM) ----------
//
// On-disk layout is base64(iv(12) || ciphertext+tag). WebCrypto appends the
// 16-byte GCM tag to the ciphertext, so we don't separate it the way node's
// crypto does — the hosted D1 starts fresh, so self-consistency is enough.

function base64ToBytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function bytesToBase64(bytes) {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

async function importKey(env) {
  const raw = base64ToBytes(String(env.ENC_KEY || ""));
  if (raw.length !== 32) {
    throw apiError(500, "ENC_KEY is missing or not 32 bytes (base64). Set it with `wrangler secret put ENC_KEY`.");
  }
  return crypto.subtle.importKey("raw", raw, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}

async function encrypt(env, plaintext) {
  const key = await importKey(env);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(plaintext)));
  const out = new Uint8Array(iv.length + ct.length);
  out.set(iv, 0);
  out.set(ct, iv.length);
  return bytesToBase64(out);
}

async function decrypt(env, b64) {
  const key = await importKey(env);
  const raw = base64ToBytes(b64);
  const iv = raw.slice(0, 12);
  const ct = raw.slice(12);
  const pt = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, ct);
  return new TextDecoder().decode(pt);
}

// ---------- Worker source generation ----------

function generateWorkerSource(manyMappings, catchAllMappings = []) {
  // manyMappings:     [{ source, destinations: string[] }]  (exact recipient)
  // catchAllMappings: [{ domain, destinations: string[] }]  (whole-domain fallback)
  const exact = manyMappings
    .map((m) => `  ${JSON.stringify(m.source)}: ${JSON.stringify(m.destinations)},`)
    .join("\n");
  const catchAll = catchAllMappings
    .map((m) => `  ${JSON.stringify(m.domain)}: ${JSON.stringify(m.destinations)},`)
    .join("\n");
  const manifest = { exact: {}, catchAll: {} };
  for (const m of manyMappings) manifest.exact[m.source] = m.destinations;
  for (const m of catchAllMappings) manifest.catchAll[m.domain] = m.destinations;
  const manifestB64 = bytesToBase64(new TextEncoder().encode(JSON.stringify(manifest)));
  return `// AUTO-GENERATED by the mappings manager. Do not edit by hand;
// re-deploy from the app instead. MAPPINGS keys are exact incoming addresses;
// CATCH_ALL keys are domains, used when no exact address matches.
${MANIFEST_START}${manifestB64}${MANIFEST_END}

const MAPPINGS = {
${exact}
};

const CATCH_ALL = {
${catchAll}
};

export default {
  async email(message, env, ctx) {
    const to = String(message.to || "").trim().toLowerCase();
    const at = to.lastIndexOf("@");
    const domain = at >= 0 ? to.slice(at + 1) : "";
    const dests = MAPPINGS[to] || CATCH_ALL[domain];
    if (!dests || dests.length === 0) {
      message.setReject("No route configured for " + to);
      return;
    }
    const results = await Promise.allSettled(dests.map((a) => message.forward(a)));
    const failures = results.filter((r) => r.status === "rejected");
    if (failures.length === dests.length) {
      message.setReject("Forwarding failed for all destinations");
    } else if (failures.length > 0) {
      console.error("Partial forward failure for " + to + ":",
        failures.map((f) => String(f.reason)).join("; "));
    }
  },
};
`;
}

// A mapping is a catch-all when its local part is exactly "*", e.g. "*@example.com".
function catchAllDomain(source) {
  const at = String(source).lastIndexOf("@");
  if (at < 0) return null;
  return source.slice(0, at) === "*" ? source.slice(at + 1).toLowerCase() : null;
}

// ---------- Cloudflare integration factory ----------

export function createCloudflare({ env, EMAIL_RE, DOMAIN_RE }) {
  const db = env.DB;

  // settings table is created by the schema.
  const getSetting = async (k) =>
    (await db.prepare("SELECT value FROM settings WHERE key = ?").bind(k).first())?.value ?? null;
  const setSetting = (k, v) =>
    db.prepare(
      "INSERT INTO settings (key, value) VALUES (?, ?) " +
        "ON CONFLICT(key) DO UPDATE SET value = excluded.value"
    ).bind(k, v).run();
  const delSetting = (k) => db.prepare("DELETE FROM settings WHERE key = ?").bind(k).run();

  async function getToken() {
    const enc = await getSetting("cf_token_enc");
    if (!enc) return null;
    try { return await decrypt(env, enc); }
    catch { return null; }
  }

  async function cf(path, init = {}) {
    const token = await getToken();
    if (!token) throw apiError(400, "No Cloudflare token configured");
    return cfWithToken(token, path, init);
  }

  async function cfWithToken(token, path, init = {}) {
    const headers = new Headers(init.headers || {});
    headers.set("Authorization", `Bearer ${token}`);
    if (!headers.has("Accept")) headers.set("Accept", "application/json");
    let res;
    try {
      res = await fetch(CF_BASE + path, { ...init, headers });
    } catch (e) {
      throw apiError(502, `Could not reach Cloudflare: ${e.message}`);
    }
    const text = await res.text();
    let body;
    try { body = text ? JSON.parse(text) : {}; }
    catch { throw apiError(502, `Non-JSON response (${res.status}) from Cloudflare`); }
    if (!res.ok || body?.success === false) {
      const errs = (body?.errors || [])
        .map((e) => `${e.code ? `[${e.code}] ` : ""}${e.message}`)
        .join("; ");
      throw apiError(res.status === 200 ? 400 : res.status,
        `Cloudflare API error (${res.status}): ${errs || res.statusText}`);
    }
    return body;
  }

  async function paginate(token, pathBase) {
    const all = [];
    let page = 1;
    while (true) {
      const sep = pathBase.includes("?") ? "&" : "?";
      const body = await cfWithToken(token, `${pathBase}${sep}per_page=${PER_PAGE}&page=${page}`);
      const batch = body.result || [];
      all.push(...batch);
      if (batch.length < PER_PAGE) break;
      if (++page > 50) break;
    }
    return all;
  }

  // ----- mappings from D1 -----

  // Read the base64 JSON manifest embedded in the deployed fan-out Worker's
  // source, so multi-destination mappings (which the rules API cannot read
  // back) can be reconstructed from Cloudflare. The worker content endpoint
  // returns raw JS (not JSON), so we fetch text and substring-scan for the
  // markers. Returns { exact, catchAll } or null when unavailable/unreadable.
  async function readWorkerManifest(token, accountId, name) {
    const path = `/accounts/${encodeURIComponent(accountId)}/workers/scripts/` +
      `${encodeURIComponent(name)}/content`;
    let res;
    try {
      res = await fetch(CF_BASE + path, { headers: { Authorization: `Bearer ${token}` } });
    } catch {
      return null;
    }
    if (!res.ok) return null; // 404 = worker not deployed yet, 403 = no read scope, etc.
    const text = await res.text();
    const i = text.indexOf(MANIFEST_START);
    if (i < 0) return null;
    const j = text.indexOf(MANIFEST_END, i + MANIFEST_START.length);
    if (j < 0) return null;
    const b64 = text.slice(i + MANIFEST_START.length, j).trim();
    try {
      const obj = JSON.parse(new TextDecoder().decode(base64ToBytes(b64)));
      return { exact: obj.exact || {}, catchAll: obj.catchAll || {} };
    } catch {
      return null;
    }
  }

  async function loadMappings() {
    const rows = (await db.prepare(
      `SELECT m.id, m.local_part AS localPart, d.name AS domain
         FROM mappings m JOIN domains d ON d.id = m.domain_id`
    ).all()).results;
    const destRows = (await db.prepare(
      "SELECT mapping_id AS mappingId, email FROM destinations"
    ).all()).results;
    const byMapping = new Map();
    for (const r of destRows) {
      if (!byMapping.has(r.mappingId)) byMapping.set(r.mappingId, []);
      byMapping.get(r.mappingId).push(String(r.email).toLowerCase());
    }
    return rows.map((m) => ({
      id: m.id,
      domain: m.domain.toLowerCase(),
      source: `${m.localPart}@${m.domain}`.toLowerCase(),
      destinations: byMapping.get(m.id) || [],
    }));
  }

  // ----- public handlers -----

  async function status() {
    const token = await getToken();
    const accountId = await getSetting("cf_account_id");
    const workerName = (await getSetting("cf_worker_name")) || DEFAULT_WORKER;
    if (!token) return { connected: false, workerName };
    let tokenStatus = null;
    let account = null;
    try {
      const v = await cfWithToken(token, "/user/tokens/verify");
      tokenStatus = v.result?.status || "unknown";
    } catch (e) {
      return { connected: true, tokenValid: false, error: e.message, accountId, workerName };
    }
    if (accountId) {
      try {
        const a = await cfWithToken(token, `/accounts/${encodeURIComponent(accountId)}`);
        account = { id: accountId, name: a.result?.name || null };
      } catch { account = { id: accountId, name: null }; }
    }
    return { connected: true, tokenValid: tokenStatus === "active", tokenStatus, account, accountId, workerName };
  }

  async function setToken(token) {
    token = String(token || "").trim();
    if (!token) throw apiError(400, "Token is required");
    const v = await cfWithToken(token, "/user/tokens/verify");
    if (v.result?.status !== "active") {
      throw apiError(400, `Token status is "${v.result?.status || "unknown"}" (expected active)`);
    }
    await setSetting("cf_token_enc", await encrypt(env, token));
    const accounts = await paginate(token, "/accounts");
    // Auto-select if exactly one account.
    if (accounts.length === 1) await setSetting("cf_account_id", accounts[0].id);
    return {
      ok: true,
      accounts: accounts.map((a) => ({ id: a.id, name: a.name })),
      accountId: await getSetting("cf_account_id"),
    };
  }

  async function clearToken() {
    await delSetting("cf_token_enc");
    await delSetting("cf_account_id");
    return { ok: true };
  }

  async function setAccount(accountId) {
    accountId = String(accountId || "").trim();
    if (!accountId) throw apiError(400, "accountId is required");
    await setSetting("cf_account_id", accountId);
    return { ok: true, accountId };
  }

  async function requireAccount() {
    const id = await getSetting("cf_account_id");
    if (!id) throw apiError(400, "No Cloudflare account selected");
    return id;
  }

  // Fetch the shared context the plan/deploy both need.
  async function gatherContext() {
    const token = await getToken();
    if (!token) throw apiError(400, "No Cloudflare token configured");
    const accountId = await requireAccount();

    const [zones, addresses] = await Promise.all([
      paginate(token, `/zones?account.id=${encodeURIComponent(accountId)}`),
      paginate(token, `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses`),
    ]);

    const zoneByName = new Map(zones.map((z) => [z.name.toLowerCase(), z]));
    const destByEmail = new Map(addresses.map((a) => [a.email.toLowerCase(), a]));
    return { token, accountId, zoneByName, destByEmail };
  }

  async function getEmailRouting(token, zoneId) {
    try {
      const r = await cfWithToken(token, `/zones/${zoneId}/email/routing`);
      const result = r.result || {};
      // Cloudflare reports enabled as a boolean, but older/edge cases only set
      // status ("ready" once MX/TXT records are live). Treat either as enabled.
      const enabled = result.enabled === true || result.status === "ready";
      return { ...result, enabled };
    } catch (e) {
      // The settings endpoint (/email/routing) is gated by a different
      // permission than the rules endpoints: some tokens can fully manage rules
      // yet get 403 here. Rather than mark the domain not-ready, fall back to an
      // endpoint we can read — the catch-all rule. If routing is genuinely
      // disabled the rules endpoints error too; if it succeeds, routing is
      // provisioned and we can manage it (which is all deploy needs).
      try {
        await cfWithToken(token, `/zones/${zoneId}/email/routing/rules/catch_all`);
        return { enabled: true, inferred: true, settingsError: e.message };
      } catch {
        // Both failed — surface the original error so it doesn't masquerade as
        // "routing disabled".
        return { enabled: false, error: e.message };
      }
    }
  }

  // Compare a Cloudflare rule action against the action we would deploy.
  // Order-insensitive on forward destination lists; case-insensitive.
  function sameAction(a, expected) {
    if (!a || a.type !== expected.type) return false;
    const norm = (v) => (v || []).map((x) => String(x).toLowerCase()).sort();
    const av = norm(a.value);
    const ev = norm(expected.value);
    return av.length === ev.length && av.every((x, i) => x === ev[i]);
  }

  // The action the deployer would set for a mapping.
  function expectedAction(m, workerName) {
    return m.destinations.length > 1
      ? { type: "worker", value: [workerName] }
      : { type: "forward", value: [m.destinations[0]] };
  }

  // The single source address a rule targets, or null if it isn't a plain
  // literal "to" rule (e.g. catch-all or a custom matcher we can't read).
  function ruleSource(rule) {
    const ms = rule.matchers || [];
    if (ms.length === 1 && ms[0].type === "literal" && ms[0].field === "to") {
      return String(ms[0].value).toLowerCase();
    }
    return null;
  }

  async function plan() {
    const { token, accountId, zoneByName, destByEmail } = await gatherContext();
    const mappings = await loadMappings();
    const workerName = (await getSetting("cf_worker_name")) || DEFAULT_WORKER;
    // Read the fan-out Worker's embedded manifest once, so worker-backed rules
    // (whose destinations aren't in the rule itself) can be reconstructed.
    const manifest = await readWorkerManifest(token, accountId, workerName);

    // ----- domains -----
    const domainNames = [...new Set(mappings.map((m) => m.domain))];
    const domains = [];
    const domainStatus = new Map();
    // For ready zones, cache the live rule list + catch-all so we can compute
    // per-mapping deploy state and detect rules that aren't in our DB.
    const zoneRules = new Map(); // domain -> { zoneId, rules:[], catchAll:obj|null }
    for (const name of domainNames) {
      const zone = zoneByName.get(name);
      let st, instructions;
      if (!zone) {
        st = "no-zone";
        instructions =
          `"${name}" is not a zone in this Cloudflare account. To manage its email here, ` +
          `add the domain to Cloudflare (Dashboard → Add a site) and update its registrar ` +
          `nameservers to the ones Cloudflare assigns, then enable Email Routing. ` +
          `Alternatively, manage this domain's email elsewhere.`;
      } else {
        const er = await getEmailRouting(token, zone.id);
        if (er.enabled) {
          st = "ready";
          // Pull the rule list + catch-all once per ready zone.
          try {
            const rules = await paginate(token, `/zones/${zone.id}/email/routing/rules`);
            let catchAll = null;
            try {
              const ca = await cfWithToken(token, `/zones/${zone.id}/email/routing/rules/catch_all`);
              catchAll = ca.result || null;
            } catch { /* catch-all unreadable; leave null */ }
            zoneRules.set(name, { zoneId: zone.id, rules, catchAll });
          } catch { /* rules unreadable; deploy state stays "unknown" */ }
        } else {
          st = "zone-no-email";
          instructions = er.error
            ? `Could not read Email Routing status for "${name}": ${er.error}. ` +
              `If email is already enabled in the dashboard, the token is likely ` +
              `missing the "Email Routing Rules: Read" (or Edit) permission for this zone.`
            : `Email Routing is not enabled for "${name}". Use "Enable email routing" below ` +
              `(this adds the required MX/TXT DNS records), or enable it in the dashboard ` +
              `(Email → Email Routing). DNS may take a few minutes to propagate.`;
        }
      }
      domainStatus.set(name, st);
      domains.push({ name, status: st, zoneId: zone?.id || null, instructions });
    }

    // ----- destinations -----
    const destEmails = [...new Set(mappings.flatMap((m) => m.destinations))];
    const destinations = destEmails.map((email) => {
      const d = destByEmail.get(email);
      let st;
      if (!d) st = "missing";
      else if (d.verified) st = "verified";
      else st = "pending";
      return { email, status: st };
    });
    const destStatus = new Map(destinations.map((d) => [d.email, d.status]));

    // Compute deploy state for one mapping against the live zone rules.
    // "deployed"  – a matching rule exists with the action we'd set.
    // "outdated"  – a rule exists but its action differs (wrong dests / type).
    // "absent"    – no matching rule exists yet.
    // "unknown"   – we couldn't read the zone's rules (permission / not ready).
    function deployStateFor(m) {
      const zr = zoneRules.get(m.domain);
      if (!zr) return "unknown";
      const expected = expectedAction(m, workerName);
      if (catchAllDomain(m.source)) {
        const action = zr.catchAll?.actions?.[0];
        if (!action || action.type === "drop") return "absent";
        return sameAction(action, expected) ? "deployed" : "outdated";
      }
      const rule = findRule(zr.rules, m.source);
      if (!rule) return "absent";
      return sameAction(rule.actions?.[0], expected) ? "deployed" : "outdated";
    }

    // ----- per-mapping readiness -----
    const ready = [];
    const blocked = [];
    for (const m of mappings) {
      const reasons = [];
      if (domainStatus.get(m.domain) !== "ready") {
        reasons.push(`domain ${m.domain} not email-ready`);
      }
      for (const e of m.destinations) {
        const s = destStatus.get(e);
        if (s === "missing") reasons.push(`destination ${e} not added`);
        else if (s === "pending") reasons.push(`destination ${e} pending verification`);
      }
      const isCatchAll = !!catchAllDomain(m.source);
      const entry = {
        id: m.id,
        source: m.source,
        domain: m.domain,
        destinations: m.destinations,
        kind: (isCatchAll ? "catch-all " : "") +
          (m.destinations.length > 1 ? "worker" : "alias"),
        catchAll: isCatchAll,
        deployState: deployStateFor(m),
      };
      if (reasons.length === 0) ready.push(entry);
      else blocked.push({ ...entry, reasons });
    }

    // ----- orphans: rules live on Cloudflare with no matching DB mapping -----
    const dbSources = new Set(mappings.map((m) => m.source));
    const dbCatchAllDomains = new Set(
      mappings.map((m) => catchAllDomain(m.source)).filter(Boolean));
    const importable = []; // forward rules we can reconstruct into the DB
    const undecipherable = []; // worker / unreadable rules — report only
    for (const [domain, zr] of zoneRules) {
      // Per-address rules.
      for (const rule of zr.rules) {
        if (rule.enabled === false) continue;
        // Cloudflare returns the catch-all rule (a single {type:"all"} matcher)
        // inside the normal rules list as well as at the dedicated catch_all
        // endpoint. Skip it here — it's handled by the catch-all branch below.
        const ms = rule.matchers || [];
        if (ms.length === 1 && ms[0].type === "all") continue;
        const src = ruleSource(rule);
        if (!src) {
          const act = rule.actions?.[0]?.type;
          const named = rule.name ? `"${rule.name}"` : "an unnamed rule";
          undecipherable.push({ domain, source: null,
            reason: `${named} matches on something other than a single "to:" `
              + `address${act ? ` (action: ${act})` : ""}, so it was probably `
              + `created by hand in the Cloudflare dashboard — review it there` });
          continue;
        }
        if (dbSources.has(src)) continue; // already represented in the DB
        const action = rule.actions?.[0];
        if (action?.type === "forward") {
          importable.push({ domain, source: src,
            destinations: (action.value || []).map((x) => String(x).toLowerCase()) });
        } else if (action?.type === "worker") {
          const dests = manifest?.exact?.[src];
          if (dests && dests.length) {
            importable.push({ domain, source: src,
              destinations: dests.map((x) => String(x).toLowerCase()) });
          } else {
            undecipherable.push({ domain, source: src,
              reason: "forwards via a Worker whose manifest couldn't be read — "
                + "destinations can't be recovered from the rule" });
          }
        } else if (action) {
          undecipherable.push({ domain, source: src, reason: `action type "${action.type}"` });
        }
      }
      // Catch-all rule.
      const ca = zr.catchAll?.actions?.[0];
      if (ca && ca.type !== "drop" && !dbCatchAllDomains.has(domain)) {
        const src = `*@${domain}`;
        if (ca.type === "forward") {
          importable.push({ domain, source: src,
            destinations: (ca.value || []).map((x) => String(x).toLowerCase()) });
        } else if (ca.type === "worker") {
          const dests = manifest?.catchAll?.[domain];
          if (dests && dests.length) {
            importable.push({ domain, source: src,
              destinations: dests.map((x) => String(x).toLowerCase()) });
          } else {
            undecipherable.push({ domain, source: src,
              reason: "catch-all forwards via a Worker whose manifest couldn't be read — "
                + "destinations can't be recovered from the rule" });
          }
        } else {
          undecipherable.push({ domain, source: src,
            reason: `catch-all action type "${ca.type}"` });
        }
      }
    }

    return {
      account: accountId,
      domains,
      destinations,
      summary: {
        total: mappings.length,
        ready: ready.length,
        blocked: blocked.length,
        deployed: [...ready, ...blocked].filter((e) => e.deployState === "deployed").length,
        outdated: [...ready, ...blocked].filter((e) => e.deployState === "outdated").length,
        absent: [...ready, ...blocked].filter((e) => e.deployState === "absent").length,
        missingDestinations: destinations.filter((d) => d.status === "missing").length,
        pendingDestinations: destinations.filter((d) => d.status === "pending").length,
        orphans: importable.length + undecipherable.length,
      },
      ready,
      blocked,
      orphans: { importable, undecipherable },
    };
  }

  // Import Cloudflare forward rules that aren't yet in the DB. `sources` is an
  // optional whitelist of source addresses to import; when omitted, every
  // importable orphan from the current plan is imported. Worker-backed and
  // unreadable rules are never imported (they're report-only).
  async function importOrphans(sources) {
    const p = await plan();
    const importable = p.orphans?.importable || [];
    const wanted = Array.isArray(sources) && sources.length
      ? new Set(sources.map((s) => String(s).toLowerCase()))
      : null;
    const targets = wanted
      ? importable.filter((o) => wanted.has(o.source))
      : importable;

    const imported = [];
    const skipped = [];
    const addedDomains = [];

    // D1 has no interactive transactions; do the (low-volume) work sequentially.
    for (const o of targets) {
      const dests = (o.destinations || []).filter((e) => EMAIL_RE.test(e));
      if (dests.length === 0) {
        skipped.push({ source: o.source, reason: "no valid forward destinations" });
        continue;
      }
      const localPart = catchAllDomain(o.source) ? "*" : o.source.slice(0, o.source.lastIndexOf("@"));
      // Ensure the (closed-list) domain exists; auto-add it since it's clearly
      // live on Cloudflare, and surface that we did so.
      let dom = await db.prepare("SELECT id FROM domains WHERE name = ? COLLATE NOCASE").bind(o.domain).first();
      if (!dom) {
        const info = await db.prepare("INSERT INTO domains (name) VALUES (?)").bind(o.domain).run();
        dom = { id: Number(info.meta.last_row_id) };
        addedDomains.push(o.domain);
      }
      let map = await db.prepare("SELECT id FROM mappings WHERE local_part = ? AND domain_id = ?").bind(localPart, dom.id).first();
      if (!map) {
        const info = await db.prepare("INSERT INTO mappings (local_part, domain_id) VALUES (?, ?)").bind(localPart, dom.id).run();
        map = { id: Number(info.meta.last_row_id) };
      }
      const stmts = [db.prepare("DELETE FROM destinations WHERE mapping_id = ?").bind(map.id)];
      for (const e of dests) {
        stmts.push(db.prepare("INSERT INTO destinations (mapping_id, email) VALUES (?, ?)").bind(map.id, e));
      }
      await db.batch(stmts);
      imported.push({ source: o.source, destinations: dests });
    }

    return {
      imported,
      skipped,
      addedDomains,
      note: imported.length
        ? `Imported ${imported.length} mapping(s) from Cloudflare` +
          (addedDomains.length ? ` (added domain(s): ${addedDomains.join(", ")})` : "") + "."
        : "Nothing to import.",
    };
  }

  async function addMissingDestinations() {
    const { token, accountId, destByEmail } = await gatherContext();
    const mappings = await loadMappings();
    const all = [...new Set(mappings.flatMap((m) => m.destinations))];
    const missing = all.filter((e) => !destByEmail.has(e));
    const added = [];
    const failed = [];
    for (const email of missing) {
      try {
        await cfWithToken(token, `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email }),
        });
        added.push(email);
      } catch (e) {
        failed.push({ email, error: e.message });
      }
    }
    return { added, failed,
      note: added.length
        ? "Cloudflare sent a verification email to each new address. Click the link in each inbox, then refresh the plan."
        : "No missing destinations to add." };
  }

  // List every Cloudflare destination address on the account with its
  // verification state. `verified` from the API is a timestamp string (or null)
  // — truthy means verified.
  async function listDestinations() {
    const token = await getToken();
    if (!token) throw apiError(400, "No Cloudflare token configured");
    const accountId = await requireAccount();
    const rows = await paginate(token, `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses`);
    const addresses = rows
      .map((a) => ({
        email: (a.email || "").toLowerCase(),
        verified: !!a.verified,
        verifiedAt: a.verified || null,
        created: a.created || null,
        id: a.tag || a.id || null,
      }))
      .sort((x, y) => x.email.localeCompare(y.email));
    return {
      accountId,
      addresses,
      summary: {
        total: addresses.length,
        verified: addresses.filter((a) => a.verified).length,
        pending: addresses.filter((a) => !a.verified).length,
      },
    };
  }

  // Add a single destination address. Cloudflare sends it a verification email;
  // the address stays "pending" until the recipient clicks the link. Adding an
  // address that already exists re-triggers the verification email.
  async function addDestination(email) {
    email = String(email || "").trim().toLowerCase();
    if (!email) throw apiError(400, "Email is required");
    if (!EMAIL_RE.test(email)) throw apiError(400, `"${email}" is not a valid email address`);
    const token = await getToken();
    if (!token) throw apiError(400, "No Cloudflare token configured");
    const accountId = await requireAccount();

    // If it already exists, report its current state instead of erroring.
    const existing = await paginate(token, `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses`);
    const found = existing.find((a) => (a.email || "").toLowerCase() === email);
    if (found) {
      return {
        ok: true,
        email,
        alreadyExisted: true,
        verified: !!found.verified,
        note: found.verified
          ? "This address is already added and verified."
          : "This address is already added but still pending. Check the inbox for the verification email from Cloudflare.",
      };
    }

    await cfWithToken(token, `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email }),
    });
    return {
      ok: true,
      email,
      alreadyExisted: false,
      verified: false,
      note: "Cloudflare sent a verification email. Click the link in that inbox, then refresh.",
    };
  }

  // Remove a destination address from the account by email. Works for both
  // pending and verified addresses (Cloudflare deletes either).
  async function removeDestination(email) {
    email = String(email || "").trim().toLowerCase();
    if (!email) throw apiError(400, "Email is required");
    const token = await getToken();
    if (!token) throw apiError(400, "No Cloudflare token configured");
    const accountId = await requireAccount();

    const existing = await paginate(token, `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses`);
    const found = existing.find((a) => (a.email || "").toLowerCase() === email);
    if (!found) {
      return { ok: true, email, removed: false, note: "That address was not on the account." };
    }
    const id = found.tag || found.id;
    if (!id) throw apiError(500, "Could not determine the address identifier to delete");

    await cfWithToken(token,
      `/accounts/${encodeURIComponent(accountId)}/email/routing/addresses/${encodeURIComponent(id)}`,
      { method: "DELETE" });
    return { ok: true, email, removed: true, note: `Removed ${email}.` };
  }

  async function enableRouting(zoneId) {
    const token = await getToken();
    if (!token) throw apiError(400, "No Cloudflare token configured");
    if (!zoneId) throw apiError(400, "zoneId is required");
    await cfWithToken(token, `/zones/${zoneId}/email/routing/enable`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: "{}",
    });
    return { ok: true, note: "Email Routing enable requested. Allow a few minutes for DNS, then refresh." };
  }

  async function putWorker(token, accountId, name, source) {
    const fd = new FormData();
    fd.append("metadata",
      new Blob([JSON.stringify({ main_module: SCRIPT_FILE })], { type: "application/json" }));
    fd.append(SCRIPT_FILE,
      new Blob([source], { type: "application/javascript+module" }), SCRIPT_FILE);
    return cfWithToken(token,
      `/accounts/${encodeURIComponent(accountId)}/workers/scripts/${encodeURIComponent(name)}/content`,
      { method: "PUT", body: fd });
  }

  // Find an existing literal "to" rule for `source` among a zone's rules.
  function findRule(rules, source) {
    return rules.find((r) =>
      (r.matchers || []).some((mm) => mm.type === "literal" && mm.field === "to" &&
        String(mm.value).toLowerCase() === source));
  }

  async function deploy() {
    const { token, accountId, zoneByName } = await gatherContext();
    const p = await plan();
    const ready = p.ready;

    const result = { worker: null, rules: [], skipped: p.blocked.map((b) => ({ source: b.source, reasons: b.reasons })) };

    if (ready.length === 0) {
      result.note = "Nothing is ready to deploy yet. Resolve the blockers above (domains / destination verification).";
      return result;
    }

    // 1. Fan-out worker for multi-destination mappings (exact + catch-all).
    const workerName = (await getSetting("cf_worker_name")) || DEFAULT_WORKER;
    const manyExact = ready.filter((m) => m.destinations.length > 1 && !catchAllDomain(m.source));
    const manyCatchAll = ready.filter((m) => m.destinations.length > 1 && catchAllDomain(m.source));
    if (manyExact.length > 0 || manyCatchAll.length > 0) {
      const source = generateWorkerSource(
        manyExact.map((m) => ({ source: m.source, destinations: m.destinations })),
        manyCatchAll.map((m) => ({ domain: catchAllDomain(m.source), destinations: m.destinations })),
      );
      await putWorker(token, accountId, workerName, source);
      result.worker = { name: workerName, mappings: manyExact.length + manyCatchAll.length };
    }

    // 2. Routing rules, grouped by zone (cache each zone's rule list once).
    const rulesByZone = new Map();
    async function rulesFor(zoneId) {
      if (!rulesByZone.has(zoneId)) {
        rulesByZone.set(zoneId, await paginate(token, `/zones/${zoneId}/email/routing/rules`));
      }
      return rulesByZone.get(zoneId);
    }

    for (const m of ready) {
      const zone = zoneByName.get(m.domain);
      if (!zone) { result.skipped.push({ source: m.source, reasons: ["zone disappeared"] }); continue; }
      const action = m.destinations.length > 1
        ? { type: "worker", value: [workerName] }
        : { type: "forward", value: [m.destinations[0]] };

      // Catch-all (*@domain) maps to Cloudflare's dedicated per-zone catch-all
      // rule, which always exists and is managed via PUT (no create/update).
      if (catchAllDomain(m.source)) {
        try {
          await cfWithToken(token, `/zones/${zone.id}/email/routing/rules/catch_all`, {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              name: `mappings-manager: catch-all ${m.domain}`,
              enabled: true,
              matchers: [{ type: "all" }],
              actions: [action],
            }),
          });
          result.rules.push({ source: m.source, kind: action.type, action: "catch-all set" });
        } catch (e) {
          result.skipped.push({ source: m.source, reasons: [e.message] });
        }
        continue;
      }

      const rulePayload = {
        name: `mappings-manager: ${m.source}`,
        enabled: true,
        matchers: [{ type: "literal", field: "to", value: m.source }],
        actions: [action],
      };
      try {
        const existingRules = await rulesFor(zone.id);
        const existing = findRule(existingRules, m.source);
        if (existing) {
          await cfWithToken(token, `/zones/${zone.id}/email/routing/rules/${existing.tag}`, {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(rulePayload),
          });
          result.rules.push({ source: m.source, kind: action.type, action: "updated" });
        } else {
          await cfWithToken(token, `/zones/${zone.id}/email/routing/rules`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(rulePayload),
          });
          result.rules.push({ source: m.source, kind: action.type, action: "created" });
        }
      } catch (e) {
        result.skipped.push({ source: m.source, reasons: [e.message] });
      }
    }

    result.note = `Deployed ${result.rules.length} rule(s)` +
      (result.worker ? ` and the fan-out worker (${result.worker.mappings} multi-destination mapping(s))` : "") +
      (result.skipped.length ? `; ${result.skipped.length} skipped.` : ".");
    return result;
  }

  return { status, setToken, clearToken, setAccount, plan, importOrphans, addMissingDestinations, listDestinations, addDestination, removeDestination, enableRouting, deploy };
}
